### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by zularizal** [Bwaim/ScoreKeeper#1]
Hi @Bwaim  , I'm a graphic designer, after I review your project, I'm interested in your project and I want to contribute by creating a logo/icon for your project. What do you think?

**Comment by Bwaim** [comment]
Hi @zularizal , it's just a training project which not will be published, but if you want to create an icon for it, feel free to do it.

**Comment by zularizal** [comment]
No prob, I am designing it.

**Comment by zularizal** [comment]
I'm sorry, I can't continue.
